services:
   nginx:
     ports: 
         - 4000:8400
     env_file: ../docker/environments/${TARGETENV}.env
     networks:
         - shared-swarm-net-dev

   
   express-gateway-service:
      env_file: ../docker/environments/${TARGETENV}.env
      ports: 
        - 8300:8300
      networks:
         - shared-swarm-net-dev
    
  #  filebeat:
  #    networks:
  #        - shared-swarm-net-dev

      
