services:
   nginx:
     ports: 
       - target: 8400 
         published: 4000
         protocol: tcp 
         mode: host
     env_file: ../docker/environments/${TARGETENV}.env
     networks:
         - shared-swarm-net-dev

   
   express-gateway-service:
      env_file: ../docker/environments/${TARGETENV}.env
      networks:
         - shared-swarm-net-dev
    
  #  filebeat:
  #    networks:
  #        - shared-swarm-net-dev

      
