services:
    nginx:
       image: ${DOCKERHUB_USER}/${APPNAME}-nginx:${TAG}
       deploy:
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.labels.role == manager]
       env_file: ../environments/common.env
       volumes:
         - nginx-logs-volume:/var/log/${APPNAME}-nginx/
  
    express-gateway-service:
      image: ${DOCKERHUB_USER}/${APPNAME}-express:${TAG}
      deploy:
        replicas: 3
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.labels.role == manager]
      env_file: ../environments/common.env
      volumes:
         - express-logs-volume:/var/log/${APPNAME}-express/

    filebeat:
      image: ${DOCKERHUB_USER}/${APPNAME}-filebeat:${TAG}
      deploy:
        restart_policy:
          condition: on-failure
        placement:
          constraints: [node.labels.role == manager]
      environment:
         - strict.perms=false
      volumes:
         - nginx-logs-volume:/var/log/${APPNAME}-nginx/:ro
         - express-logs-volume:/var/log/${APPNAME}-express/:ro


volumes:
  mongo-data:
  nginx-logs-volume:
  express-logs-volume:

networks:
   shared-swarm-net-dev:
      external: true
   shared-swarm-net-prod:
      external: true

  # In this example, mongo-data is a named volume that ensures all data written 
  # by the MongoDB container to /data/db (MongoDB's default data directory) is saved persistently 
  # on the host system, even if the mongodb container is removed or recreated.